plugin: amazon.aws.aws_ec2

regions:
  - us-west-1

filters:
  tag:Role: app
  tag:Env: prod
  instance-state-name: running

keyed_groups:
  - key: tag_Role        # changed
    prefix: role

compose:
  ansible_host: public_ip_address
